
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.ListIterator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author adriankato
 */
public class GUIFrame extends javax.swing.JFrame {

    /**
     * Creates new form GUIFrame
     */
    public GUIFrame() {
        initComponents();
        bookingCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
        bookingDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getDay().toArray()));
        bookingFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));

        flightStatusFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));
        flightStatusDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getDay().toArray()));
        waitlistStatusDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getDay().toArray()));

        customerStatusCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
        cancelCustomerCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
        cancelCustomerDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getDay().toArray()));
        dropFlightFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        addCustomerButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addCustomerResults = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bookingCustomerComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        bookingFlightComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        bookingDayComboBox = new javax.swing.JComboBox<>();
        bookingButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookingResults = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        flightStatusButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        flightStatusTextArea = new javax.swing.JTextArea();
        flightStatusFlightComboBox = new javax.swing.JComboBox<>();
        flightStatusDayComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        waitlistStatusButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        waitlistStatusTextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        waitlistStatusDayComboBox = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        flightNameTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        flightSeatTextField = new javax.swing.JTextField();
        addFlightButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        addFlightResults = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        flightDaySpinner = new javax.swing.JSpinner();
        addDayButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        addDayResults = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        customerStatusCustomerComboBox = new javax.swing.JComboBox<>();
        customerStatusButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        customerStatusTextArea = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cancelCustomerCustomerComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cancelCustomerDayComboBox = new javax.swing.JComboBox<>();
        cancelCustomerButton = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        cancelCustomerResults = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        dropFlightFlightComboBox = new javax.swing.JComboBox<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        dropFlightResults = new javax.swing.JTextArea();
        dropFlightButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flight Scheduler");
        setPreferredSize(new java.awt.Dimension(959, 599));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Flight Scheduler");

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel2.setText("Enter Customer Name:");

        customerNameTextField.setColumns(20);

        addCustomerButton.setText("Add Customer");
        addCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtonActionPerformed(evt);
            }
        });

        addCustomerResults.setEditable(false);
        addCustomerResults.setColumns(20);
        addCustomerResults.setRows(5);
        jScrollPane1.setViewportView(addCustomerResults);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(addCustomerButton)
                        .addGap(400, 400, 400))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCustomerButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Customer", jPanel1);

        jLabel3.setText("Customer:");

        bookingCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Flight:");

        bookingFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Day:");

        bookingDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bookingButton.setText("Book");
        bookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingButtonActionPerformed(evt);
            }
        });

        bookingResults.setEditable(false);
        bookingResults.setColumns(20);
        bookingResults.setRows(5);
        jScrollPane2.setViewportView(bookingResults);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bookingButton)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookingCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookingFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookingDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookingCustomerComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bookingFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bookingDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bookingButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Book Flight", jPanel2);

        flightStatusButton.setText("Get Status");
        flightStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightStatusButtonActionPerformed(evt);
            }
        });

        flightStatusTextArea.setEditable(false);
        flightStatusTextArea.setColumns(20);
        flightStatusTextArea.setRows(5);
        jScrollPane4.setViewportView(flightStatusTextArea);

        flightStatusFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        flightStatusDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Flight:");

        jLabel7.setText("Day:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(168, 168, 168)
                        .addComponent(jLabel7)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(flightStatusFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(flightStatusDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)))
                .addComponent(flightStatusButton)
                .addGap(171, 171, 171))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightStatusFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightStatusDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightStatusButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Flight Status", jPanel3);

        waitlistStatusButton.setText("Get Status");
        waitlistStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waitlistStatusButtonActionPerformed(evt);
            }
        });

        waitlistStatusTextArea.setEditable(false);
        waitlistStatusTextArea.setColumns(20);
        waitlistStatusTextArea.setRows(5);
        jScrollPane5.setViewportView(waitlistStatusTextArea);

        jLabel8.setText("Day:");

        waitlistStatusDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(waitlistStatusDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308)
                .addComponent(waitlistStatusButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waitlistStatusButton)
                    .addComponent(waitlistStatusDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Waitlist Status", jPanel4);

        jLabel9.setText("Enter Flight Name:");

        flightNameTextField.setColumns(10);

        jLabel10.setText("Enter Number of Seats:");

        flightSeatTextField.setColumns(5);

        addFlightButton.setText("Add Flight");
        addFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightButtonActionPerformed(evt);
            }
        });

        addFlightResults.setEditable(false);
        addFlightResults.setColumns(20);
        addFlightResults.setRows(5);
        jScrollPane3.setViewportView(addFlightResults);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addFlightButton)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(316, 316, 316)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(flightNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(flightSeatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)))
                .addContainerGap(332, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(flightNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(flightSeatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addComponent(addFlightButton)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Flight", jPanel5);

        jLabel11.setText("Pick a day:");

        flightDaySpinner.setModel(new javax.swing.SpinnerDateModel());

        addDayButton.setText("Add Day");
        addDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDayButtonActionPerformed(evt);
            }
        });

        addDayResults.setEditable(false);
        addDayResults.setColumns(20);
        addDayResults.setRows(5);
        jScrollPane6.setViewportView(addDayResults);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addDayButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(151, 151, 151)))
                .addGap(40, 40, 40)
                .addComponent(flightDaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 216, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(flightDaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addDayButton)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Day", jPanel6);

        jLabel12.setText("Customer:");

        customerStatusCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        customerStatusButton.setText("Get Status");
        customerStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerStatusButtonActionPerformed(evt);
            }
        });

        customerStatusTextArea.setEditable(false);
        customerStatusTextArea.setColumns(20);
        customerStatusTextArea.setRows(5);
        jScrollPane7.setViewportView(customerStatusTextArea);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(customerStatusButton)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(customerStatusCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(customerStatusCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(customerStatusButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer Status", jPanel7);

        jLabel13.setText("Customer:");

        cancelCustomerCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Day:");

        cancelCustomerDayComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cancelCustomerButton.setText("Cancel Customer");
        cancelCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCustomerButtonActionPerformed(evt);
            }
        });

        cancelCustomerResults.setEditable(false);
        cancelCustomerResults.setColumns(20);
        cancelCustomerResults.setRows(5);
        jScrollPane8.setViewportView(cancelCustomerResults);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(64, 64, 64)
                                .addComponent(cancelCustomerCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(228, 228, 228)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelCustomerDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(cancelCustomerButton)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cancelCustomerCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cancelCustomerDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(cancelCustomerButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Cancel Customer", jPanel8);

        jLabel15.setText("Flight:");

        dropFlightFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dropFlightResults.setEditable(false);
        dropFlightResults.setColumns(20);
        dropFlightResults.setRows(5);
        jScrollPane9.setViewportView(dropFlightResults);

        dropFlightButton.setText("Drop Flight");
        dropFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropFlightButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(dropFlightFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(dropFlightButton))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(dropFlightFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropFlightButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Drop Flight", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtonActionPerformed
        // TODO add your handling code here:
        Customer.addNewCustomer(customerNameTextField.getText());
        addCustomerResults.setText("Customer " + customerNameTextField.getText() + " has been added.");

        // Redesign ComboBox
        bookingCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
        customerStatusCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
        cancelCustomerCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
    }//GEN-LAST:event_addCustomerButtonActionPerformed

    private void bookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingButtonActionPerformed
        // TODO add your handling code here:
        java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());

        BookingEntry bookingEntry = new BookingEntry((String) bookingCustomerComboBox.getSelectedItem(),
                (String) bookingFlightComboBox.getSelectedItem(), (Date) bookingDayComboBox.getSelectedItem(),
                currentTimestamp);

        int numberOfSeats = Flight.getFlightSeats(bookingEntry.getFlight(), bookingEntry.getDay());

        if (numberOfSeats < Flight.getMaxSeatCount(bookingEntry.getFlight())) {
            BookingQueries bookingQueries = new BookingQueries();

            int result = bookingQueries.addBooking(bookingEntry, bookingEntry.getTimestamp());
            if (result == 1) {

                bookingResults.setText(bookingEntry.getCustomer() + " has been booked flight " + bookingEntry.getFlight() + " on " + bookingEntry.getDay() + ".");

            }
        } else {
            Waitlist waitlist = new Waitlist();

            int result = waitlist.addWaitlist(bookingEntry, bookingEntry.getTimestamp());

            if (result == 1) {
                bookingResults.setText(bookingEntry.getCustomer() + " has been waitlisted for a flight on " + bookingEntry.getDay() + ".");

            }
        }

    }//GEN-LAST:event_bookingButtonActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void flightStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightStatusButtonActionPerformed
        // TODO add your handling code here:
        BookingQueries bookingQueries = new BookingQueries();
        String printStatus;
        printStatus = bookingQueries.statusByFlightDay((String) flightStatusFlightComboBox.getSelectedItem(), (Date) flightStatusDayComboBox.getSelectedItem());
        flightStatusTextArea.setText(printStatus);
    }//GEN-LAST:event_flightStatusButtonActionPerformed

    private void waitlistStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waitlistStatusButtonActionPerformed
        // TODO add your handling code here:
        Waitlist waitlist = new Waitlist();
        String printStatus;
        printStatus = waitlist.statusByDay((Date) waitlistStatusDayComboBox.getSelectedItem());
        waitlistStatusTextArea.setText(printStatus);
    }//GEN-LAST:event_waitlistStatusButtonActionPerformed

    private void addFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightButtonActionPerformed
        // TODO add your handling code here:
        Flight.addFlight(flightNameTextField.getText(), Integer.parseInt(flightSeatTextField.getText()));
        addFlightResults.setText("Flight " + flightNameTextField.getText()
                + " has been added.");

        //Redesign ComboBox
        bookingFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));
        flightStatusFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));
        dropFlightFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));
    }//GEN-LAST:event_addFlightButtonActionPerformed

    private void addDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDayButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String spinnerValue = formater.format(flightDaySpinner.getValue());
        Date day = Date.valueOf(spinnerValue);
        Day.addDay(day);
        addDayResults.setText(day + " has been added to Days.");

        //Redesign ComboBox
        bookingDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getDay().toArray()));
        flightStatusDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getDay().toArray()));
        waitlistStatusDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getDay().toArray()));
        cancelCustomerDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getDay().toArray()));

    }//GEN-LAST:event_addDayButtonActionPerformed

    private void customerStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerStatusButtonActionPerformed
        // TODO add your handling code here:
        String printStatus;
        printStatus = Customer.getCustomerStatus(customerStatusCustomerComboBox.getSelectedItem().toString());
        customerStatusTextArea.setText(printStatus);
    }//GEN-LAST:event_customerStatusButtonActionPerformed

    private void cancelCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCustomerButtonActionPerformed
        // TODO add your handling code here:
        java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());

        BookingQueries bookingQueries = new BookingQueries();
        Waitlist waitlist = new Waitlist();
        bookingQueries.cancelBooking((String) cancelCustomerCustomerComboBox.getSelectedItem(), (Date) cancelCustomerDayComboBox.getSelectedItem());
        cancelCustomerResults.setText((String) cancelCustomerCustomerComboBox.getSelectedItem() + "'s booking on " + cancelCustomerDayComboBox.getSelectedItem() + " has been cancelled. \n");
        if ((waitlist.statusByDay((Date) cancelCustomerDayComboBox.getSelectedItem())) != "Name" + "\t" + "Flight" + "\t\t" + "Timestamp" + "\n") {
            BookingEntry copyEntry = new BookingEntry();
            copyEntry = waitlist.getWaitlist((Date) cancelCustomerDayComboBox.getSelectedItem());

            bookingQueries.addBooking(waitlist.getWaitlist((Date) cancelCustomerDayComboBox.getSelectedItem()), currentTimestamp);
            cancelCustomerResults.append(copyEntry.getCustomer() + " has been booked a flight on " + copyEntry.getFlight() + " from the waitlist. \n");
            waitlist.cancelWaitlistCustomerDay(waitlist.getWaitlist((Date) cancelCustomerDayComboBox.getSelectedItem()));
            cancelCustomerResults.append(copyEntry.getCustomer() + " has been removed from the waitlist on " + copyEntry.getDay() + ".");
        }
    }//GEN-LAST:event_cancelCustomerButtonActionPerformed

    private void dropFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropFlightButtonActionPerformed
        // TODO add your handling code here:
        java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        BookingQueries bookingQueries = new BookingQueries();
        Waitlist waitlist = new Waitlist();

        //String waitlistStatus = waitlist.statusByFlight((String)dropFlightFlightComboBox.getSelectedItem());
        //String bookingStatus = bookingQueries.statusByFlight((String)dropFlightFlightComboBox.getSelectedItem());
        Flight.cancelFlight((String) dropFlightFlightComboBox.getSelectedItem());
        dropFlightResults.setText("Flight " + dropFlightFlightComboBox.getSelectedItem().toString() + " has been cancelled. \n");

        while (waitlist.statusByFlight((String) dropFlightFlightComboBox.getSelectedItem()) != "Name" + "\t" + "Flight" + "\t\t" + "Timestamp" + "\n") {
            BookingEntry bookingEntry = new BookingEntry();
            bookingEntry = waitlist.getWaitlistbyFlight((String) dropFlightFlightComboBox.getSelectedItem());
            waitlist.cancelWaitlistFlight(waitlist.getWaitlistbyFlight((String) dropFlightFlightComboBox.getSelectedItem()));
            dropFlightResults.append(bookingEntry.getCustomer() + " has been removed from the waitlist for flight " + bookingEntry.getFlight() + ". \n");
        }

        while (bookingQueries.statusByFlight((String) dropFlightFlightComboBox.getSelectedItem()) != "Name" + "\t\t" + "Timestamp" + "\n") {
            BookingEntry bookingToBeDeleted = new BookingEntry();
            BookingEntry vacantBooking = new BookingEntry();
            String emptyFlight;

            ArrayList<BookingEntry> vacantBookingList = new ArrayList<BookingEntry>(bookingQueries.getVacantBooking(bookingQueries.getBookingByFlight((String) dropFlightFlightComboBox.getSelectedItem())));
            bookingToBeDeleted = bookingQueries.getBookingByFlight((String) dropFlightFlightComboBox.getSelectedItem());
            ArrayList<String> emptyFlightsList = new ArrayList(bookingQueries.getEmptyFlights(bookingToBeDeleted.getFlight(), bookingToBeDeleted.getDay()));

            if (!(vacantBookingList.isEmpty())) {
                vacantBooking = vacantBookingList.get(0);
                bookingQueries.addRebooking(bookingQueries.getBookingByFlight((String) dropFlightFlightComboBox.getSelectedItem()), vacantBooking, currentTimestamp);
                dropFlightResults.append(bookingToBeDeleted.getCustomer() + " has been rebooked to flight " + vacantBooking.getFlight() + " on " + vacantBooking.getDay() + ". \n");
                bookingQueries.cancelBookingByEntry(bookingQueries.getBookingByFlight((String) dropFlightFlightComboBox.getSelectedItem()));
                dropFlightResults.append(bookingToBeDeleted.getCustomer() + "'s flight " + bookingToBeDeleted.getFlight() + " on " + bookingToBeDeleted.getDay() + " has been cancelled. \n");

            } else if (!(emptyFlightsList.isEmpty())) {
                emptyFlight = emptyFlightsList.get(0);
                bookingQueries.bookEmptyFlights(bookingQueries.getBookingByFlight((String) dropFlightFlightComboBox.getSelectedItem()), emptyFlight, currentTimestamp);
                dropFlightResults.append(bookingToBeDeleted.getCustomer() + " has been rebooked to flight " + emptyFlight + " on " + bookingToBeDeleted.getDay() + ". \n");
                bookingQueries.cancelBookingByEntry(bookingQueries.getBookingByFlight((String) dropFlightFlightComboBox.getSelectedItem()));
                dropFlightResults.append(bookingToBeDeleted.getCustomer() + "'s flight " + bookingToBeDeleted.getFlight() + " on " + bookingToBeDeleted.getDay() + " has been cancelled. \n");

            } else {
                bookingQueries.cancelBookingByEntry(bookingQueries.getBookingByFlight((String) dropFlightFlightComboBox.getSelectedItem()));
                dropFlightResults.append(bookingToBeDeleted.getCustomer() + "'s flight " + bookingToBeDeleted.getFlight() + " on " + bookingToBeDeleted.getDay() + " has been cancelled. \n");
            }
        }

        bookingFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));
        flightStatusFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));
        dropFlightFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));
    }//GEN-LAST:event_dropFlightButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JTextArea addCustomerResults;
    private javax.swing.JButton addDayButton;
    private javax.swing.JTextArea addDayResults;
    private javax.swing.JButton addFlightButton;
    private javax.swing.JTextArea addFlightResults;
    private javax.swing.JButton bookingButton;
    private javax.swing.JComboBox<String> bookingCustomerComboBox;
    private javax.swing.JComboBox<String> bookingDayComboBox;
    private javax.swing.JComboBox<String> bookingFlightComboBox;
    private javax.swing.JTextArea bookingResults;
    private javax.swing.JButton cancelCustomerButton;
    private javax.swing.JComboBox<String> cancelCustomerCustomerComboBox;
    private javax.swing.JComboBox<String> cancelCustomerDayComboBox;
    private javax.swing.JTextArea cancelCustomerResults;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JButton customerStatusButton;
    private javax.swing.JComboBox<String> customerStatusCustomerComboBox;
    private javax.swing.JTextArea customerStatusTextArea;
    private javax.swing.JButton dropFlightButton;
    private javax.swing.JComboBox<String> dropFlightFlightComboBox;
    private javax.swing.JTextArea dropFlightResults;
    private javax.swing.JSpinner flightDaySpinner;
    private javax.swing.JTextField flightNameTextField;
    private javax.swing.JTextField flightSeatTextField;
    private javax.swing.JButton flightStatusButton;
    private javax.swing.JComboBox<String> flightStatusDayComboBox;
    private javax.swing.JComboBox<String> flightStatusFlightComboBox;
    private javax.swing.JTextArea flightStatusTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton waitlistStatusButton;
    private javax.swing.JComboBox<String> waitlistStatusDayComboBox;
    private javax.swing.JTextArea waitlistStatusTextArea;
    // End of variables declaration//GEN-END:variables
}
